// plugins/medlab.js

export const generateReport = async (reportData, docsAPI) => {
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric'
  });

  const title = `MedLab AI Report - ${currentDate}`;
  const contentBlocks = [
    {
      text: `MedLab AI Report\n\n`,
      style: { bold: true, fontSize: 18 }
    },
    {
      text: `Generated on: ${currentDate}\n\n`,
      style: { fontSize: 12 }
    },
    {
      text: `AI Lab Summary:\n`,
      style: { bold: true, fontSize: 14 }
    },
    {
      text: `${reportData.aiLabSummary || 'No summary provided.'}\n\n`,
      style: { fontSize: 12 }
    },
    {
      text: `Additional Notes:\n`,
      style: { bold: true, fontSize: 14 }
    },
    {
      text: `${reportData.additionalNotes || 'None.'}\n\n`,
      style: { fontSize: 12 }
    },
    {
      text: `\n---\nGenerated by MedLab Plugin`,
      style: { fontSize: 10 }
    }
  ];

  const doc = await docsAPI.createDocument(title);
  await docsAPI.addFormattedContent(doc.documentId, contentBlocks);

  return {
    success: true,
    documentId: doc.documentId,
    url: `https://docs.google.com/document/d/${doc.documentId}/edit`,
    title
  };
};

export default { generateReport };
